spring:
  jpa:
    database-platform: mysql
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create   #just for testing - destroy and create new db after server restart

  datasource:
    url: jdbc:mysql://localhost:3306/hotels?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver